{{- if .Values.azureACRServicePrinciple.enabled -}}
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkYXRhaW5uLmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiI0YjY1NzBmYi04OTA0LTRhMDYtODlhMi01OTNjZjA4NDQzZmIiLCJwYXNzd29yZCI6IlR4TE1VanZjWUR2SjJTTzhJNlduYjJhQ2pSOUhIaH5UaFUiLCJhdXRoIjoiTkdJMk5UY3dabUl0T0Rrd05DMDBZVEEyTFRnNVlUSXROVGt6WTJZd09EUTBNMlppT2xSNFRFMVZhblpqV1VSMlNqSlRUemhKTmxkdVlqSmhRMnBTT1VoSWFINVVhRlU9In19fQ==
kind: Secret
metadata:
  name: az-acr-service-principal-credentials

type: kubernetes.io/dockerconfigjson
  {{- end }}
