apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simpleaccounts-io-strapi-backend.fullname" . }}-db-credentials
  namespace: {{ .Values.nameSpaces }}
type: Opaque
data:
  databaseClient: {{ .Values.data.databaseClient }}
  databaseName: {{ .Values.data.databaseName }}
  databaseHost: {{ .Values.data.databaseHost }}
  databasePort: {{ .Values.data.databasePort }}
  databaseUsername: {{ .Values.data.databaseUsername }}
  databasePassword: {{ .Values.data.databasePassword }}
