apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: azurefile-csi-nfs-premium
    volume.beta.kubernetes.io/storage-provisioner: file.csi.azure.com
  finalizers:
  - kubernetes.io/pvc-protection
  name: {{ include "simpleaccounts-io-strapi-backend.fullname" . }}-rw-k8s-pvc
  namespace: {{ .Values.nameSpaces }}
spec:
  accessModes:
    - {{ .Values.accessMode }}
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: {{ .Values.nameSpaces }}-rw-k8s-pv
