apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  finalizers:
    - kubernetes.io/pv-protection
    - external-attacher/file-csi-azure-com
  name: {{ include "simpleaccounts-io-strapi-backend.fullname" . }}-rw-k8s-pv
spec:
  accessModes:
    - {{ .Values.accessMode }}
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: {{ .Values.nameSpaces }}-rw-k8s-pvc
    namespace: {{ .Values.nameSpaces }}
  csi:
    driver: file.csi.azure.com
    fsType: ext4
    volumeAttributes:
      protocol: nfs
      resourceGroup: dataInn-k8s-RG
      skuName: Premium_LRS
      storageAccount: datainnk8sfilestorage
    volumeHandle: dataInn-k8s-RG#datainnk8sfilestorage#{{ .Values.persistentVolumePath }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi-nfs-premium
  volumeMode: Filesystem
