apiVersion: v1
kind: Service
metadata:
  name: {{ include "simpleaccounts-io-strapi-backend.fullname" . }}
  namespace: {{ .Values.nameSpaces }}
  labels:
    {{- include "simpleaccounts-io-strapi-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "simpleaccounts-io-strapi-backend.selectorLabels" . | nindent 4 }}
